name: Sync, Build & Deploy MK4

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'    # every day at 02:00 UTC (04:00 Berlin)

jobs:
  sync-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      # 2. Upstream merge
      - name: Add & fetch prusa3d upstream
        run: |
          git remote add upstream https://github.com/prusa3d/Prusa-Firmware-Buddy.git
          git fetch upstream
      - name: Merge upstream/master
        run: |
          git checkout master
          git merge upstream/master --no-edit
      - name: Push merged master
        run: git push origin master

      # 3. Install system-level build tools
      - name: Install ARM toolchain & build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-none-eabi \
            make \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi

      # 4. Set up Python & Python deps
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python requirements
        run: python -m pip install -r requirements.txt

      # 5. (Optional) Show workspace contents for debug
      - name: List all files
        run: ls -R .

      # 6. Build MK4 in release mode
      - name: Build MK4 (release)
        run: python utils/build.py --preset mk4 --build-type release

      # 7. Upload artifact
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: PrusaBuddy-MK4-release
          path: build/products/**

      # 8. GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/products/**/*.bbf
          asset_name: PrusaBuddy-MK4-${{ github.sha }}.bbf
          asset_content_type: application/octet-stream
